services:
  ros2:
    image: ros2-humble-ws
    # platform: linux/amd64   # keep if you built amd64; remove if arm64
    container_name: ros2-dev
    working_dir: /home/${USER}/ros2_ws
    stdin_open: true
    tty: true
    volumes:
      # your code & persistent build artifacts
      - ./src:/home/${USER}/ros2_ws/src
      - ros2_build:/home/${USER}/ros2_ws/build
      - ros2_install:/home/${USER}/ros2_ws/install
      - ros2_log:/home/${USER}/.ros

      # === Git + SSH (key-file approach) ===
      - ${HOME}/.gitconfig:/home/${USER}/.gitconfig:ro
      - ${HOME}/.ssh/id_ed25519:/home/${USER}/.ssh/id_ed25519:ro
      - ${HOME}/.ssh/id_ed25519.pub:/home/${USER}/.ssh/id_ed25519.pub:ro
      - ${HOME}/.ssh/known_hosts:/home/${USER}/.ssh/known_hosts:ro
    # environment:
    #   SSH_AUTH_SOCK: /ssh-agent

volumes:
  ros2_build:
  ros2_install:
  ros2_log:

