services:
  ros2:
    build:
      context: .
      args:
        USERNAME: ros
        USER_ID: 1000
        GID: 1000
    image: redhotchili/olin-comprobo-ros2:humble
    container_name: ros2-dev
    working_dir: /home/ros/ros2_ws
    stdin_open: true
    tty: true
    init: true
    environment:
      ROS_DOMAIN_ID: "0"
    volumes:
      - ./src:/home/ros/ros2_ws/src
      - ros2_build:/home/ros/ros2_ws/build
      - ros2_install:/home/ros/ros2_ws/install
      - ros2_log:/home/ros/.ros

      # Mount your host git/ssh read-only into a cache dir
      - ${HOME}/.gitconfig:/cache/git/.gitconfig:ro
      - ${HOME}/.ssh/id_ed25519:/cache/ssh/id_ed25519:ro
      - ${HOME}/.ssh/id_ed25519.pub:/cache/ssh/id_ed25519.pub:ro
      - ${HOME}/.ssh/known_hosts:/cache/ssh/known_hosts:ro

    # Copy into writable ~/.ssh, set perms, then start a shell
    command: >
      bash -lc '
        mkdir -p ~/.ssh;
        [ -f /cache/ssh/id_ed25519 ] && cp /cache/ssh/id_ed25519 ~/.ssh/ && chmod 600 ~/.ssh/id_ed25519 || true;
        [ -f /cache/ssh/id_ed25519.pub ] && cp /cache/ssh/id_ed25519.pub ~/.ssh/ && chmod 644 ~/.ssh/id_ed25519.pub || true;
        [ -f /cache/ssh/known_hosts ] && cp /cache/ssh/known_hosts ~/.ssh/ && chmod 644 ~/.ssh/known_hosts || true;
        [ -f /cache/git/.gitconfig ] && cp /cache/git/.gitconfig ~/.gitconfig || true;
        echo -e "Host github.com\n  HostName github.com\n  User git\n  IdentitiesOnly yes\n  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config;
        chmod 700 ~/.ssh; chmod 600 ~/.ssh/config;
        exec bash
      '

volumes:
  ros2_build:
  ros2_install:
  ros2_log:
