services:
  ros2:
    image: redhotchili/olin-comprobo-ros2:humble
    container_name: ros2-dev
    network_mode: "host"                 # enable host networking so DDS discovery & GUIs work smoothly
    working_dir: /home/ros/ros2_ws
    stdin_open: true
    tty: true
    init: true
    environment:
      DISPLAY: ${DISPLAY}                # pass host X display
      QT_X11_NO_MITSHM: "1"              # avoid MIT-SHM issues in containers
      XAUTHORITY: /tmp/.docker.xauth     # point Qt to the mounted Xauthority
      ROS_DOMAIN_ID: "0"                 # keep your chosen domain id
      # RMW_IMPLEMENTATION: rmw_fastrtps_cpp   # (optional) set explicitly; ensure all shells match
      # ROS_LOCALHOST_ONLY: "1"                # (optional) keep traffic on loopback only
    volumes:
      # Workspace
      - ${HOME}/ros2_ws:/home/ros/ros2_ws

      # X11 sockets + Xauthority for GUI apps like rviz2/rqt
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/tmp/.docker.xauth:ro

      # Git/SSH cache (optional)
      - ${HOME}/.gitconfig:/cache/git/.gitconfig:ro
      - ${HOME}/.ssh/id_ed25519:/cache/ssh/id_ed25519:ro
      - ${HOME}/.ssh/id_ed25519.pub:/cache/ssh/id_ed25519.pub:ro
      - ${HOME}/.ssh/known_hosts:/cache/ssh/known_hosts:ro

    devices:
      - /dev/dri:/dev/dri                 # GPU/DRI (helps with OpenGL acceleration)

    # Run as your host user to avoid Xauthority permission issues (Linux only)
    user: "${UID}:${GID}"

    command: >
      bash -lc '
        mkdir -p ~/.ssh;
        [ -f /cache/ssh/id_ed25519 ] && cp /cache/ssh/id_ed25519 ~/.ssh/ && chmod 600 ~/.ssh/id_ed25519 || true;
        [ -f /cache/ssh/id_ed25519.pub ] && cp /cache/ssh/id_ed25519.pub ~/.ssh/ && chmod 644 ~/.ssh/id_ed25519.pub || true;
        [ -f /cache/ssh/known_hosts ] && cp /cache/ssh/known_hosts ~/.ssh/ && chmod 644 ~/.ssh/known_hosts || true;
        [ -f /cache/git/.gitconfig ] && cp /cache/git/.gitconfig ~/.gitconfig || true;
        echo -e "Host github.com\n  HostName github.com\n  User git\n  IdentitiesOnly yes\n  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config;
        chmod 700 ~/.ssh; chmod 600 ~/.ssh/config;
        exec bash
      '
