services:
  ros2:
    image: ros2-humble-ws
    # platform: linux/amd64   # keep if you built amd64; remove if arm64
    container_name: ros2-dev
    working_dir: /home/junpark/ros2_ws
    stdin_open: true
    tty: true

    volumes:
      # your code & persistent build artifacts
      - ./src:/home/junpark/ros2_ws/src
      - ros2_build:/home/junpark/ros2_ws/build
      - ros2_install:/home/junpark/ros2_ws/install
      - ros2_log:/home/junpark/.ros

      # === Git + SSH (key-file approach) ===
      - ${HOME}/.gitconfig:/home/junpark/.gitconfig:ro
      - ${HOME}/.ssh/id_ed25519:/home/junpark/.ssh/id_ed25519:ro
      - ${HOME}/.ssh/id_ed25519.pub:/home/junpark/.ssh/id_ed25519.pub:ro
      - ${HOME}/.ssh/known_hosts:/home/junpark/.ssh/known_hosts:ro

    # If you ever switch back to agent-forwarding, use these instead:
    # volumes:
    #   - /run/host-services/ssh-auth.sock:/ssh-agent
    # environment:
    #   SSH_AUTH_SOCK: /ssh-agent

volumes:
  ros2_build:
  ros2_install:
  ros2_log:

